- azure/azure-pr-pipeline.yml
Producer support issue - https://dev.azure.com/NHSD-APIM/API%20Platform/_build/results?buildId=31215&view=logs&j=8a735c4f-3944-5036-8568-d56e3864e126&t=2f8e1ac2-18c0-5407-f2d6-3ec21197e712&l=82
> APM-2016 Fix internal-dev-sandbox deployments

- specification/e-referrals-service-api.yaml
> ERSSUP-54338 - Finalise the overview section of OAS file

- proxies/live/apiproxy/policies/AssignMessage.Remove.nhsd-correlation-id-header.xml
- proxies/live/apiproxy/policies/AssignMessage.Remove.nhsd-request-id-header.xml
- proxies/live/apiproxy/policies/AssignMessage.Remove.x-request-id-header.xml
- proxies/live/apiproxy/policies/AssignMessage.SetFlagCustomHeaderXRequestId.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.CorrelationHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.TransactionID.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-ers-business-function.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-ers-ods-code.xml
- proxies/live/apiproxy/targets/ers-target.xml
…e eRS Apigee configuration]-[HR]
> [ERSSUP-54726]-[]-[Add support for client supported tracing IDs to the eRS Apigee configuration]-[HR]

- README.md
> ERSSUP-54838 Repository README.md

- proxies/live/apiproxy/policies/AssignMessage.AddAsidHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
- proxies/live/apiproxy/policies/AssignMessage.AddIssuerHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.AddPayloadToPing.xml
- proxies/live/apiproxy/policies/AssignMessage.AddUserIdHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.OAuthPolicyErrorResponse.xml
- proxies/live/apiproxy/policies/AssignMessage.Remove.nhsd-correlation-id-header.xml
- proxies/live/apiproxy/policies/AssignMessage.Remove.nhsd-request-id-header.xml
- proxies/live/apiproxy/policies/AssignMessage.Remove.x-request-id-header.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.CorrelationHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.TransactionID.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-ers-business-function.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-ers-ods-code.xml
- proxies/live/apiproxy/targets/ers-target.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddIssuerHeader.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddPayloadToPing.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddUserIdHeader.xml
…e eRS Apigee configuration]-[HR]
> [ERSSUP-54726]-[]-[Add support for client supported tracing IDs to the eRS Apigee configuration - review changes]-[HR]

- azure/azure-release-pipeline.yml
- proxies/live/apiproxy/policies/AssignMessage.AddAsidHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
- proxies/live/apiproxy/policies/AssignMessage.AddIssuerHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.AddPayloadToPing.xml
- proxies/live/apiproxy/policies/AssignMessage.AddUserIdHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.OAuthPolicyErrorResponse.xml
- proxies/live/apiproxy/policies/AssignMessage.PopulateAsidFromApp.xml
- proxies/live/apiproxy/policies/AssignMessage.Remove.nhsd-correlation-id-header.xml
- proxies/live/apiproxy/policies/AssignMessage.Remove.nhsd-request-id-header.xml
- proxies/live/apiproxy/policies/AssignMessage.Remove.x-request-id-header.xml
- proxies/live/apiproxy/policies/AssignMessage.SetFlagCustomHeaderXRequestId.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.CorrelationHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.TransactionID.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-ers-business-function.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-ers-ods-code.xml
- proxies/live/apiproxy/targets/ers-target.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddIssuerHeader.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddPayloadToPing.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddUserIdHeader.xml
> Misc changes for first integration.

- sandbox/src/mocks/PasNotRespondingOperationOutcome.json
- sandbox/src/mocks/PasRespondedWithErrorOperationOutcome.json
- sandbox/src/mocks/bookOrDeferAppointment/requests/BookingWithNamedClinician.json
- sandbox/src/mocks/bookOrDeferAppointment/requests/DeferralBookingAttemptProblem.json
- sandbox/src/mocks/bookOrDeferAppointment/requests/DeferralWithSlotReference.json
- sandbox/src/mocks/bookOrDeferAppointment/requests/MinimalBooking.json
- sandbox/src/mocks/bookOrDeferAppointment/requests/MinimalDeferral.json
- sandbox/src/mocks/bookOrDeferAppointment/responses/BookingWithNamedClinician.json
- sandbox/src/mocks/bookOrDeferAppointment/responses/DeferralBookingAttemptProblem.json
- sandbox/src/mocks/bookOrDeferAppointment/responses/DeferralWithSlotReference.json
- sandbox/src/mocks/bookOrDeferAppointment/responses/MinimalBooking.json
- sandbox/src/mocks/bookOrDeferAppointment/responses/MinimalDeferral.json
- sandbox/src/routes/bookOrDeferAppointment.js
- sandbox/src/routes/index.js
- sandbox/src/services/mockResponseProvider.js
- scripts/populate_placeholders.py
- specification/components/schemas/eRS-Appointment.yaml
- specification/components/schemas/responses/Conflict.yaml
- specification/components/schemas/responses/bookOrDeferAppointment/201Response.yaml
- specification/components/schemas/responses/bookOrDeferAppointment/422Response.yaml
- specification/components/schemas/responses/bookOrDeferAppointment/502Response.yaml
- specification/components/schemas/responses/bookOrDeferAppointment/504Response.yaml
- specification/components/schemas/responses/generatePatientLetter/422Response.yaml
- specification/components/schemas/responses/maintainReferralLetter/422Response.yaml
- specification/e-referrals-service-api.yaml
> [ERSSUP-55130]-[]-[OAS documentation for ERSSUP-54157: APIM User calls e-RS Endpoint to Book or Defer Appointment]-[HR]

- azure/azure-release-pipeline.yml
This permits e-RS engineers with access to the Azure pipelines to approve
releases into all environments except production.
> Set approver environment to manual-approval-ptl.

- proxies/live/apiproxy/policies/OAuthV2.VerifyAccessToken.xml
- proxies/sandbox/apiproxy/policies/OAuthV2.VerifyAccessToken.xml
> [ERSSUP-55732]-[HR/JW]-[Validate AAL3 Security Level]-[RG]

- proxies/live/apiproxy/policies/AssignMessage.RemoveAndAddAsidHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.RemoveAndAddUserIdHeader.xml
- proxies/live/apiproxy/targets/ers-target.xml
> [ERSSUP-55958]-[JW/AO]-[Remove ers-user-id header]-[RG]

- azure/azure-release-pipeline.yml
- proxies/live/apiproxy/policies/KeyValueMapOperations.GetSharedSecuredVariables.xml
- proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/live/apiproxy/resources/jsc/SetStatusResponse.js
> [ERSSUP-56070]-[]-[Add _ping to CallHeathCheck]-[DMW]

- azure/azure-release-pipeline.yml
> ERSSUP-58241

- manifest_template.yml
> ERSSUP-58531

- sandbox/src/routes/uploadFileToDocumentStore.js
- specification/components/schemas/file/FileContentTypeSchema.yaml
- specification/e-referrals-service-api.yaml
> [ERSSUP-58314]-[]-[Update XAPI spec w.r.t. ERSSUP-56694 (DICOM Content-Type)]-[HR]

- README.md
> Hotfix Rollback Testing ERSSUP-58383

- README.md
> ERSSUP-58383

- specification/e-referrals-service-api.yaml
> [ERSSUP-58677]-[]-[OAS document updated with user-restricted text]-[RG]

- scripts/populate_placeholders.py
- specification/e-referrals-service-api.yaml
> [ERSSUP-59131]-[]-[Fix broken links in OAS documentation]-[FV]

- sandbox/src/routes/uploadFileToDocumentStore.js
> [ERSSUP-58876]-[]-[Sandbox API issue fixed for A020]-[RG]

- tests/smoke/configuration/config.py
> APM-2016 Fix smoke tests

- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- manifest_template.yml
- proxies/live/apiproxy/targets/ers-target.xml
> Clean test for ERSSUP-57222

- azure/azure-release-pipeline.yml
> ERSSUP-59379 - Hotfix Back to Develop

- specification/e-referrals-service-api.yaml
> Apm 0001 add service level section

- manifest_template.yml
https://nhsd-jira.digital.nhs.uk/browse/APM-2869
Associating the relevant products that can use mock-oauth with the corrisponding identity-service proxy
> APM-2869 Allow products access to mock oauth

- Makefile
- poetry.lock
- pyproject.toml
- scripts/validate_oas_examples.py
- specification/components/schemas/AppointmentSlotBundle.yaml
> ERSSUP-57563 xAPI APIM: Implementing example validation using openapi-core in the APIM repo

- sandbox/src/mocks/acceptReferral/responses/ExampleResponse.json
- sandbox/src/mocks/cancelAppointmentActionLater/responses/MinimalExampleDBS.json
- sandbox/src/mocks/cancelAppointmentActionLater/responses/MinimalExampleIBS.json
- sandbox/src/mocks/cancelAppointmentActionLater/responses/PriorityChangeAndWithAttachmentsDBS.json
- sandbox/src/mocks/convertAdviceAndGuidanceToReferral/responses/NoAttachments.json
- sandbox/src/mocks/convertAdviceAndGuidanceToReferral/responses/WithAttachments.json
- sandbox/src/mocks/createReferral/responses/ReferralRequestTwentyServices.json
- sandbox/src/mocks/maintainReferralLetter/responses/ReferralRequestWithMultipleDocumentReferences.json
- sandbox/src/mocks/maintainReferralLetter/responses/ReferralRequestWithSingleDocumentReference.json
- sandbox/src/mocks/maintainReferralLetter/responses/ReferralRequestWithUpdatedDocumentReferences.json
- sandbox/src/mocks/recordTriageOutcome/responses/AcceptReferBookLater.json
- sandbox/src/mocks/recordTriageOutcome/responses/AttachmentIncluded.json
- sandbox/src/mocks/recordTriageOutcome/responses/ReturnToReferrerWithAdvice.json
- sandbox/src/mocks/rejectReferral/responses/ExampleResponseDbs.json
- sandbox/src/mocks/rejectReferral/responses/ExampleResponseIbs.json
- sandbox/src/mocks/retrieveReferralRequest/responses/BookedDBS.json
- sandbox/src/mocks/retrieveReferralRequest/responses/BookedIBS.json
- sandbox/src/mocks/retrieveReferralRequest/responses/ConvertedFromAdviceAndGuidance.json
- sandbox/src/mocks/retrieveReferralRequest/responses/DeferredToProvider.json
- sandbox/src/mocks/retrieveReferralRequest/responses/Unbooked.json
- sandbox/src/mocks/retrieveReferralRequest/responses/WithRelatedReferral.json
- sandbox/src/mocks/sendAdviceAndGuidanceResponse/responses/AttachmentIncluded.json
- sandbox/src/mocks/sendAdviceAndGuidanceResponse/responses/RequireFurtherInformation.json
- sandbox/src/mocks/sendAdviceAndGuidanceResponse/responses/ReturnToReferrerWithAdvice.json
- specification/components/schemas/eRS-ServiceSearchCriteria-Parameters.yaml
- specification/components/schemas/extensions/Extension-eRS-ServiceSummaryView.yaml
> Omit organisation from xAPI responses

- sandbox/src/mocks/changeShortlistAndSendForTriage/requests/MinimalRequest.json
- sandbox/src/mocks/changeShortlistAndSendForTriage/responses/MinimalRequest.json
- specification/components/schemas/eRS-ChangeShortlistAndSendForTriage-Request-Parameters.yaml
- specification/components/schemas/eRS-ChangeShortlistAndSendForTriage-Response-Parameters.yaml
- specification/components/schemas/responses/changeShortlistAndSendForTriage/200Response.yaml
- specification/e-referrals-service-api.yaml
> [ERSSUP-59980]-[]-[Rename Change Shortlist Profile URLs]-[RG]

- proxies/live/apiproxy/policies/AssignMessage.Swap.NHSD-eRS-On-Behalf-Of-User-ID.xml
- proxies/live/apiproxy/targets/ers-target.xml
- tests/integration/test_headers.py
> ERSSUP-59667 - Policy to translate NHSD-eRS-On-Behalf-Of-User-ID header to x-ers-obo-user-id

- proxies/live/apiproxy/policies/AssignMessage.Swap.NHSD-eRS-On-Behalf-Of-User-ID.xml
- proxies/live/apiproxy/targets/ers-target.xml
- tests/integration/test_headers.py
> ERSSUP-59667_NEW - Policy to translate NHSD-eRS-On-Behalf-Of-User-ID header to x-ers-obo-user-id

- azure/templates/ers-integration-tests.yml
- azure/templates/run-tests.yml
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/data.py
- tests/integration/test_headers.py
New tests added which hit the actual eRS endpoint and verify the headers received
> Further eRS APIM integration / end to end tests

- sandbox/src/mocks/getService/responses/sampleServiceWithMinimumAttributes.json
- sandbox/src/mocks/searchForServices/responses/searchServiceWithMinmumalAttributes.json
- specification/components/schemas/eRS-HealthcareService.yaml
> [ERSSUP-59892]-[]-[Spec Validation Issue Fixed]-[RG]

- specification/e-referrals-service-api.yaml
…ion section to include eRS specific headers]-[NM]
> [ERSSUP-59914]-[]-[Update API-M documentation Security and Authorisation section to include eRS specific headers]-[NM]

- sandbox/src/mocks/cancelReferral/requests/cancelReferralExample.json
- sandbox/src/mocks/cancelReferral/responses/ExampleCancelledReferral.json
- sandbox/src/mocks/cancelReferral/responses/ExampleCancelledReferralWithAppoinment.json
- sandbox/src/routes/cancelReferral.js
- sandbox/src/routes/index.js
- sandbox/src/services/mockResponseProvider.js
- scripts/populate_placeholders.py
- specification/components/schemas/eRS-CancelReferral-Request-Parameters.yaml
- specification/components/schemas/eRS-CancelReferral-Response-Parameters.yaml
- specification/components/schemas/eRS-ReferralRequest.yaml
- specification/components/schemas/responses/cancelReferral/200Response.yaml
- specification/components/schemas/responses/cancelReferral/422Response.yaml
- specification/components/schemas/responses/cancelReferral/502Response.yaml
- specification/components/schemas/responses/cancelReferral/504Response.yaml
- specification/e-referrals-service-api.yaml
> [ERSSUP-57623]-[DW/JW]-[OAS Modelling for Cancel Referral]-[RG]

- specification/e-referrals-service-api.yaml
> [ERSSUP-60700]-[]-[Add wording to xAPI endpoint A029 Available actions for user list]-[FV]

- specification/e-referrals-service-api.yaml
> [ERSSUP-60668]-[]-[Fix headers of endpoints A005 and A024]-[FV]

- sandbox/src/mocks/cancelAppointmentActionLater/responses/MinimalExampleDBS.json
- sandbox/src/mocks/cancelAppointmentActionLater/responses/MinimalExampleIBS.json
- sandbox/src/mocks/cancelAppointmentActionLater/responses/PriorityChangeAndWithAttachmentsDBS.json
- sandbox/src/mocks/convertAdviceAndGuidanceToReferral/responses/NoAttachments.json
- sandbox/src/mocks/convertAdviceAndGuidanceToReferral/responses/WithAttachments.json
- sandbox/src/mocks/recordTriageOutcome/responses/AcceptReferBookLater.json
- sandbox/src/mocks/recordTriageOutcome/responses/AttachmentIncluded.json
- sandbox/src/mocks/recordTriageOutcome/responses/ReturnToReferrerWithAdvice.json
- sandbox/src/mocks/rejectReferral/responses/ExampleResponseDbs.json
- sandbox/src/mocks/rejectReferral/responses/ExampleResponseIbs.json
- sandbox/src/mocks/retrieveReferralRequest/responses/ConvertedFromAdviceAndGuidance.json
> [ERSSUP-61101]-[]-[Defining State Example Update]-[RG]

- specification/e-referrals-service-api.yaml
> [ERSSUP-61118]-[JW]-[Add defining state overview content]-[RG]

- specification/e-referrals-service-api.yaml
> [ERSSUP-61118]-[JW]-[Defining State Overview Text Update]-[RG]

- Makefile
- sandbox/package-lock.json
- sandbox/package.json
- sandbox/src/app.js
- Removed inert library, which was dependent on ammo
- Installed @hapi/inert library, which is now dependent on @hapi/ammo
>     "@hapi/inert": {
>       "version": "6.0.5",
>       "resolved": "https://registry.npmjs.org/@hapi/inert/-/inert-6.0.5.tgz",
>       "integrity": "sha512-eVAdUVhJLmmXLM/Zt7u5H5Vzazs9GKe4zfPK2b97ePHEfs3g/AQkxHfYQjJqMy11hvyB7a21Z6rBEA0R//dtXw==",
>       "requires": {
>         "@hapi/ammo": "5.x.x",
>         "@hapi/boom": "9.x.x",
>         "@hapi/bounce": "2.x.x",
>         "@hapi/hoek": "9.x.x",
>         "@hapi/validate": "1.x.x",
>         "lru-cache": "^6.0.0"
>       }
- Vulnerability (Denial of Service in ammo) from ammo package has disappeared when running `$ npm audit`
- Also fixed the `make sandbox` command
:information_source: This …
> [ERSSUP-61143]-[]-[Install @hapi/inert and remove inert library]-[FV]

- .github/dependabot.yml
> [ERSSUP-61233]-[]-[Basic dependabot config]-[]

- sandbox/src/routes/getStatus.js
> [ERSSUP-58534]-[]-[Fix for Sandbox Failure]-[RG]

- ecs-proxies-deploy.yml
- package-lock.json
- package.json
> [ERSSUP-62632]-[]-[Update apigee tool]-[DMW]

- manifest_template.yml
- proxies/live/apiproxy/policies/AssignMessage.QuotaErrorResponse.xml
- proxies/live/apiproxy/policies/AssignMessage.SetBinaryRateLimitIdentifier.xml
- proxies/live/apiproxy/policies/AssignMessage.SpikeArrestErrorResponse.xml
- proxies/live/apiproxy/policies/FlowCallout.ApplyRateLimiting.xml
- proxies/live/apiproxy/policies/Quota.Binary.xml
- proxies/live/apiproxy/policies/SpikeArrest.Binary.xml
- proxies/live/apiproxy/policies/SpikeArrest.xml
- proxies/live/apiproxy/policies/javascript.IsBinaryPath.xml
- proxies/live/apiproxy/resources/jsc/IsBinaryPath.js
- proxies/live/apiproxy/targets/ers-target.xml
> [ERSSUP-62204]-[]-[New rate limit strategy]-[FV]

- pyproject.toml
> [ERSSUP-63493]-[]-[Remove comment in authors section]-[DMW]

- sandbox/src/mocks/r4/searchForServices/responses/searchServiceWithEmptyResponse.json
- sandbox/src/mocks/r4/searchForServices/responses/searchServiceWithMaxAndMinAttributes.json
- sandbox/src/mocks/r4/searchForServices/responses/searchServiceWithMinmumalAttributes.json
- sandbox/src/mocks/stu3/acceptReferral/responses/ExampleResponse.json
- sandbox/src/mocks/stu3/cancelReferral/responses/CancelledBookedReferralReferrerCancellation.json
- sandbox/src/mocks/stu3/cancelReferral/responses/CancelledReferralIntendPrivateWithoutComment.json
- sandbox/src/mocks/stu3/cancelReferral/responses/CancelledReferralPatientOther.json
- sandbox/src/mocks/stu3/cancelReferral/responses/CancelledReferralRaisedInError.json
- sandbox/src/mocks/stu3/cancelReferral/responses/CancelledReferralResolvedDeferralIntendPrivateWithComment.json
- sandbox/src/mocks/stu3/cancelReferral/responses/CancelledReferralWithCancelledBookingNoLongerRequired.json
- sandbox/src/mocks/stu3/changeShortlist/requests/UnbookedReferral.json
- sandbox/src/mocks/stu3/changeShortlist/requests/UnbookedReferralMultipleServices.json
- sandbox/src/mocks/stu3/changeShortlist/responses/UnbookedReferral.json
- sandbox/src/mocks/stu3/changeShortlist/responses/UnbookedReferralMultipleServices.json
- sandbox/src/mocks/stu3/changeShortlistAndSendForTriage/requests/MinimalRequest.json
- sandbox/src/mocks/stu3/retrieveAdviceAndGuidanceConversation/SingleMessageFromReferrer.json
- sandbox/src/mocks/stu3/retrieveAppointment/responses/Cancelled.json
- sandbox/src/mocks/stu3/updateAppointment/requests/CancellationInvalidReason.json
- sandbox/src/mocks/stu3/updateAppointment/requests/CancellationReasonAndMandatoryComment.json
- sandbox/src/mocks/stu3/updateAppointment/requests/CancellationReasonOnlyCommentMandatory.json
- sandbox/src/mocks/stu3/updateAppointment/requests/MinimalCancellationReasonOnlyCommentNotMandatory.json
- sandbox/src/mocks/stu3/updateAppointment/responses/CancellationReasonAndMandatoryComment.json
- sandbox/src/mocks/stu3/updateAppointment/responses/MinimalCancellationReasonOnlyCommentNotMandatory.json
- specification/components/r4/schemas/responses/searchForService/200Response.yaml
Removed references to v1 and FHIR on URL for sandbox examples of A013,
A031, A032, A034, A035 and A038 sandbox examples as well as from A034 200Response.yaml
> [ERSSUP-61283]-[JW]-[Remove v1 & FHIR on URL]-[NS]

- proxies/live/apiproxy/policies/AssignMessage.Set.x-ers-access-mode-header-app-restricted.xml
- proxies/live/apiproxy/policies/AssignMessage.Set.x-ers-access-mode-header-user-restricted.xml
- proxies/live/apiproxy/targets/ers-target.xml
- tests/integration/test_app_restricted.py
- tests/integration/test_headers.py
> [ERSSUP-62263]-[]-[Adding header for access mode]-[JG]

- .github/workflows/combine-prs.yml
> [ERSSUP-64897]-[]-[Workflow to combine dependabot PRs]-[DMW]

- .github/workflows/combine-prs.yml
> [ERSSUP-64897]-[]-[Remove colon from branch names]-[DMW]

- specification/e-referrals-service-api.yaml
> API Specs - add Errors section

- sandbox/src/mocks/NotFoundOutcome.txt
- sandbox/src/mocks/stu3/NotFoundOutcome.txt
- sandbox/src/routes/r4/retrieveHealthcareService.js
- sandbox/src/routes/r4/services/mockResponseProvider.js
- specification/components/r4/schemas/endpoints/a030-retrieve-business-functions.yaml
- specification/components/r4/schemas/endpoints/a035-search-for-healthcare-services.yaml
- specification/components/r4/schemas/responses/searchForService/200Response.yaml
- specification/components/stu3/schemas/endpoints/a006-retrieve-attachment.yaml
- specification/components/stu3/schemas/endpoints/a012-maintain-referral-letter.yaml
- specification/components/stu3/schemas/endpoints/a015-retrieve-appointment-slots.yaml
> ERSSUP-65716 - OAS Bug Fixes

- azure/azure-release-pipeline.yml
- manifest_template.yml
> [ERSSUP-65817]-[]-[Configure APIM to deploy to the DEP environment]-[]

- manifest_template.yml
> [ERSSUP-65817]-[]-[Fix manifest template]-[DMW]

- manifest_template.yml
> Merge Fix For Manifest Template To 17.0

- specification/components/r4/schemas/endpoints/a041-search-service-request.yaml
> [ERSSUP-66638]-[]-[Added warning message in A041 documentation]-[AP]

- Makefile
- macros/manifest_macros.yml
- manifest_template.yml
> [ERSSUP-66050]-[AO]-[Refactor manifest_template - 2]-[DMW]

- proxies/live/apiproxy/policies/AssignMessage.Swap.CorrelationHeader.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.NHSD-eRS-On-Behalf-Of-User-ID.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.TransactionID.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-end-user-organisation-ods.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-ers-business-function.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-ers-comm-rule-org.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-ers-file-name.xml
- proxies/live/apiproxy/policies/AssignMessage.Swap.nhsd-ers-referral-id.xml
- proxies/live/apiproxy/policies/VerifyApiKey.XApiKey.xml
- tests/integration/test_headers.py
> [ERSSUP-66713]-[]-[APIM - comma truncates file name on upload]-[DMW]

- .github/CODEOWNERS
> [ERSSUP-59513]-[]-[CODEOWNERS File to restrict approval reviews]-[DMW]

- poetry.lock
Reverts NHSDigital/e-referrals-service-api#842
> Revert "pip(deps): bump urllib3 from 1.26.15 to 2.0.2"

- sandbox/src/mocks/stu3/bookOrDeferAppointment/requests/TriageDeferral.json
- sandbox/src/mocks/stu3/bookOrDeferAppointment/responses/TriageDeferral.json
- sandbox/src/routes/stu3/services/mockResponseProvider.js
- specification/components/stu3/schemas/endpoints/a004-retrieve-reference-data.yaml
- specification/components/stu3/schemas/endpoints/a010-patient-service-search.yaml
- specification/components/stu3/schemas/endpoints/a016-book-or-defer-appointment.yaml
- specification/components/stu3/schemas/endpoints/a021-create-referral-request-and-send-for-triage.yaml
- specification/components/stu3/schemas/endpoints/a029-available-actions-for-user-list.yaml
- specification/components/stu3/schemas/endpoints/a032-change-shortlist-and-send-for-triage.yaml
- specification/components/stu3/schemas/endpoints/a038-retrieve-appointment.yaml
- specification/components/stu3/schemas/responses/bookOrDeferAppointment/201Response.yaml
- specification/e-referrals-service-api.yaml
- tests/sandbox/stu3/test_a016_book_or_defer_appointment.py
> [ERSSUP-69334]-[]-[ERSSUP-67504 - Book Defer Changes]-[DMW]

- scripts/rhel_setup_environment.sh
> [ERSSUP-69887]-[]-[Fix urllib incompatibility on dev VM]-[DMW]

- specification/components/stu3/schemas/responses/Locked.yaml
> [ERSSUP-67516]-[]-[Updated API document for 423 Locked Response]-[RG]

- Makefile
- scripts/ubuntu_clean_environment.sh
- scripts/ubuntu_setup_environment.sh
> [ERSSUP-70289]-[]-[Update APIM setup scripts to run against WSL]-[DMW]

- pyproject.toml
> [ERSSUP-70944]-[AO]-[remove empty homepage from pyproject.toml]-[DMW]

- specification/components/r4/schemas/endpoints/a037-retrieve-healthcare-service-version.yaml
- specification/components/stu3/schemas/queryParameters/Status.yaml
Adding missing 'Overview' heading to A037 and provided value for A015 empty 'status' request query parameter
> [ERSSUP-68876/70358]-[JW]-[Fix for 68876 and 70358]-[NS]

- sandbox/src/mocks/stu3/getCodeSystem/responses/AppointmentCancellationReasonCodeSystem.json
- sandbox/src/mocks/stu3/getCodeSystem/responses/AppointmentNonAttendanceReasonCodeSystem.json
- sandbox/src/mocks/stu3/getCodeSystem/responses/ClinicTypeCodeSystem.json
- sandbox/src/mocks/stu3/getCodeSystem/responses/PriorityCodeSystem.json
- sandbox/src/mocks/stu3/getCodeSystem/responses/ReferralCancellationReasonCodeSystem.json
- sandbox/src/mocks/stu3/getCodeSystem/responses/SpecialtyCodeSystem.json
- scripts/populate_placeholders.py
- specification/components/r4/schemas/endpoints/a040-retrieve-practitioner-info.yaml
- specification/components/stu3/schemas/CodeSystem.yaml
- specification/components/stu3/schemas/endpoints/a005-retrieve-referral-request.yaml
- specification/e-referrals-service-api.yaml
> [ERSSUP-72310]-[]-[Update OAS files to remove Beta status]-[DMW]

- sandbox/src/mocks/stu3/bookOrDeferAppointment/requests/TriageDeferral.json
- sandbox/src/mocks/stu3/bookOrDeferAppointment/responses/TriageDeferral.json
- sandbox/src/mocks/stu3/changeShortlist/requests/UnbookedReferralMixedShortlist.json
- sandbox/src/mocks/stu3/changeShortlist/responses/UnbookedReferralMixedShortlist.json
- sandbox/src/mocks/stu3/createReferral/requests/RequestMixedShortlist.json
- sandbox/src/mocks/stu3/createReferral/responses/ReferralRequestMixedShortlist.json
- sandbox/src/routes/stu3/services/mockResponseProvider.js
- specification/components/stu3/schemas/endpoints/a004-retrieve-reference-data.yaml
- specification/components/stu3/schemas/endpoints/a010-patient-service-search.yaml
- specification/components/stu3/schemas/endpoints/a011-create-referral.yaml
- specification/components/stu3/schemas/endpoints/a016-book-or-defer-appointment.yaml
- specification/components/stu3/schemas/endpoints/a021-create-referral-request-and-send-for-triage.yaml
- specification/components/stu3/schemas/endpoints/a029-available-actions-for-user-list.yaml
- specification/components/stu3/schemas/endpoints/a031-change-shortlist.yaml
- specification/components/stu3/schemas/endpoints/a032-change-shortlist-and-send-for-triage.yaml
- specification/components/stu3/schemas/endpoints/a038-retrieve-appointment.yaml
- specification/components/stu3/schemas/responses/bookOrDeferAppointment/201Response.yaml
- specification/components/stu3/schemas/responses/changeShortlist/200Response.yaml
- specification/components/stu3/schemas/responses/createReferral/201Response.yaml
- tests/sandbox/stu3/test_a016_book_or_defer_appointment.py
> RM35 OAS Changes

- sandbox/src/mocks/stu3/bookOrDeferAppointment/requests/TriageDeferral.json
- sandbox/src/mocks/stu3/bookOrDeferAppointment/responses/TriageDeferral.json
- sandbox/src/mocks/stu3/changeShortlist/requests/UnbookedReferralMixedShortlist.json
- sandbox/src/mocks/stu3/changeShortlist/responses/UnbookedReferralMixedShortlist.json
- sandbox/src/mocks/stu3/createReferral/requests/RequestMixedShortlist.json
- sandbox/src/mocks/stu3/createReferral/responses/ReferralRequestMixedShortlist.json
- sandbox/src/routes/stu3/services/mockResponseProvider.js
- specification/components/stu3/schemas/endpoints/a004-retrieve-reference-data.yaml
- specification/components/stu3/schemas/endpoints/a010-patient-service-search.yaml
- specification/components/stu3/schemas/endpoints/a011-create-referral.yaml
- specification/components/stu3/schemas/endpoints/a016-book-or-defer-appointment.yaml
- specification/components/stu3/schemas/endpoints/a021-create-referral-request-and-send-for-triage.yaml
- specification/components/stu3/schemas/endpoints/a029-available-actions-for-user-list.yaml
- specification/components/stu3/schemas/endpoints/a031-change-shortlist.yaml
- specification/components/stu3/schemas/endpoints/a032-change-shortlist-and-send-for-triage.yaml
- specification/components/stu3/schemas/endpoints/a038-retrieve-appointment.yaml
- specification/components/stu3/schemas/responses/bookOrDeferAppointment/201Response.yaml
- specification/components/stu3/schemas/responses/changeShortlist/200Response.yaml
- specification/components/stu3/schemas/responses/createReferral/201Response.yaml
- tests/sandbox/stu3/test_a016_book_or_defer_appointment.py
> RM35 OAS changes and fixes

- specification/components/stu3/schemas/eRS-ServiceSearchCriteria-Parameters.yaml
- specification/components/stu3/schemas/extensions/Extension-eRS-ServiceSummaryView.yaml
- specification/components/stu3/schemas/parameters/AgeAndGenderAppropriate.yaml
Updates/adds descriptions to various API schemas with inclusive wording around gender vs sex
Jira ticket: https://nhsd-jira.digital.nhs.uk/browse/ERSSUP-72623
> [ERSSUP-72623]-[DW]-[Update gender/sex wording]-[AST]

- sandbox/src/mocks/stu3/retrieveReferralRequest/responses/WithAdditionalRequirements.json
- specification/components/stu3/schemas/eRS-ReferralRequest.yaml
> [ERSSUP-71237]-[JW]-[Added missing ReferralRequest.Specialty]-[NS]

- sandbox/src/mocks/r4/getService/responses/sampleServiceWithFullAttributes.json
- sandbox/src/mocks/r4/searchForServices/responses/searchServiceWithMaxAndMinAttributes.json
- specification/components/r4/schemas/eRS-HealthcareService.yaml
> [ERSSUP-68398]-[JW]-[Edited schema file and examples]-[NS]

- sandbox/src/mocks/r4/getService/responses/sampleServiceWithFullAttributes.json
- sandbox/src/mocks/r4/searchForServices/responses/searchServiceWithMaxAndMinAttributes.json
- specification/components/r4/schemas/eRS-HealthcareService.yaml
Reverts NHSDigital/e-referrals-service-api#1624
> Revert "[ERSSUP-68398]-[JW]-[Edited schema file and examples]-[NS]"

- sandbox/src/mocks/r4/getService/responses/sampleServiceWithFullAttributes.json
- sandbox/src/mocks/r4/searchForServices/responses/searchServiceWithMaxAndMinAttributes.json
- specification/components/r4/schemas/eRS-HealthcareService.yaml
Reverts NHSDigital/e-referrals-service-api#1666
> Restore [ERSSUP-68398]-[JW]-[Edited schema file and examples]-[NS]

- sandbox/src/mocks/stu3/acceptReferral/responses/ExampleResponse.json
- sandbox/src/mocks/stu3/cancelAppointmentActionLater/responses/MinimalExampleDBS.json
- sandbox/src/mocks/stu3/cancelAppointmentActionLater/responses/MinimalExampleIBS.json
- sandbox/src/mocks/stu3/cancelAppointmentActionLater/responses/PriorityChangeAndWithAttachmentsDBS.json
- sandbox/src/mocks/stu3/changeShortlist/responses/UnbookedReferral.json
- sandbox/src/mocks/stu3/changeShortlist/responses/UnbookedReferralMixedShortlist.json
- sandbox/src/mocks/stu3/changeShortlist/responses/UnbookedReferralMultipleServices.json
- sandbox/src/mocks/stu3/changeShortlistAndSendForTriage/responses/MinimalRequest.json
- sandbox/src/mocks/stu3/createReferral/requests/MinimalRequest.json
- sandbox/src/mocks/stu3/createReferral/requests/MinimalRequestWithReferringClinician.json
- sandbox/src/mocks/stu3/createReferral/requests/RequestTwentyServices.json
- sandbox/src/mocks/stu3/createReferral/responses/ReferralRequest.json
- sandbox/src/mocks/stu3/createReferral/responses/ReferralRequestTwentyServices.json
- sandbox/src/mocks/stu3/createReferralAndSendForTriage/responses/ReferralRequest.json
- sandbox/src/mocks/stu3/createReferralAndSendForTriage/responses/ReferralRequestWithNamedClinician.json
- sandbox/src/mocks/stu3/recordTriageOutcome/responses/AcceptReferBookLater.json
- sandbox/src/mocks/stu3/recordTriageOutcome/responses/AttachmentIncluded.json
- sandbox/src/mocks/stu3/recordTriageOutcome/responses/ReturnToReferrerWithAdvice.json
- sandbox/src/mocks/stu3/rejectReferral/responses/ExampleResponseDbs.json
- sandbox/src/mocks/stu3/rejectReferral/responses/ExampleResponseIbs.json
- sandbox/src/mocks/stu3/retrieveReferralRequest/responses/BookedDBS.json
- sandbox/src/mocks/stu3/retrieveReferralRequest/responses/BookedIBS.json
- sandbox/src/mocks/stu3/retrieveReferralRequest/responses/DeferredToProvider.json
- sandbox/src/mocks/stu3/retrieveReferralRequest/responses/WithAdditionalRequirements.json
- sandbox/src/mocks/stu3/retrieveReferralRequest/responses/WithRelatedReferral.json
- specification/components/stu3/schemas/eRS-CreateReferral-Parameters.yaml
- specification/components/stu3/schemas/eRS-ReferralRequest.yaml
- specification/components/stu3/schemas/extensions/Extension-eRS-eReferralPathwayStart.yaml
- specification/components/stu3/schemas/parameters/EReferralPathwayStart.yaml
> ERSSUP-72781 - Referral Pathway Start Date

- proxies/live/apiproxy/policies/AssignMessage.Set.nhsd-ers-business-function-header-app-restricted.xml
- sandbox/src/mocks/stu3/retrieveWorklist/requests/FilteredByService.json
- sandbox/src/mocks/stu3/retrieveWorklist/responses/FilteredByService.json
- specification/components/r4/schemas/endpoints/a033-retrieve-healthcare-service.yaml
- specification/components/r4/schemas/endpoints/a035-search-for-healthcare-services.yaml
- specification/components/r4/schemas/endpoints/a037-retrieve-healthcare-service-version.yaml
- specification/components/r4/schemas/headers/request/BusinessFunctionOnlyUserRestricted.yaml
- specification/components/r4/schemas/headers/request/OdsCodeOnlyUserRestricted.yaml
- specification/components/stu3/schemas/eRS-FetchWorklist-Parameters.yaml
- specification/components/stu3/schemas/endpoints/a004-retrieve-reference-data.yaml
- specification/components/stu3/schemas/endpoints/a005-retrieve-referral-request.yaml
- specification/components/stu3/schemas/endpoints/a006-retrieve-attachment.yaml
- specification/components/stu3/schemas/endpoints/a007-retrieve-clinical-information.yaml
- specification/components/stu3/schemas/endpoints/a008-retrieve-worklist.yaml
- specification/components/stu3/schemas/endpoints/a024-retrieve-advice-and-guidance.yaml
- specification/components/stu3/schemas/endpoints/a025-retrieve-advice-and-guidance-conversation.yaml
- specification/components/stu3/schemas/endpoints/a043-retrieve-advice-and-guidance-overview-pdf.yaml
- specification/components/stu3/schemas/parameters/ListType.yaml
- specification/components/stu3/schemas/responses/retrieveWorklist/200Response.yaml
- specification/e-referrals-service-api.yaml
- tests/conftest.py
- tests/integration/test_app_restricted.py
> Combined branch for ERSSUP-73552, ERSSUP-74395, ERSSUP-73911

- sandbox/src/mocks/stu3/STU3-Forbidden.json
- specification/components/stu3/schemas/responses/Forbidden.yaml
> [ERSSUP-77308]-[]-[Update STU3 Forbidden]-[iDMW]

- tests/asserts.py
- tests/integration/test_app_restricted.py
> [ERSSUP-80635]-[FV]-[Check for body in 403 response]-[DMW]

- pyproject.toml
> [ERSSUP-81151]-[]-[Set package mode false]-[DMW]

- redocly.yaml
> ERSSUP-77272 - Remove warning for missing tag description from OAS vvalidation
